=== nmrML/nmrML/tools/Parser_and_Converters/Java/converter/src/xsd/CvMapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2006 rel. 3 U (http://www.altova.com) by Samuel Kerrien (EBI) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="CvMapping">
		<xs:annotation>
			<xs:documentation>Document related to a given data exchange schema or model, it describes all the associations between the specific schema section and the appropriate CV terms. </xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CvReferenceList">
					<xs:annotation>
						<xs:documentation>Comprehensive list of CVs that are required by a schema or model. </xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="CvReference" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Description of a CV or ontology resource.</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="cvSourceVersion" use="optional"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="CvMappingRuleList">
					<xs:annotation>
						<xs:documentation>Comprehensive list of associations between a model and CVs.</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element ref="CvMappingRule" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>Single mapping rule between a specific element of the xsd and controlled vocabularies listed as allowed values on the CvTerm element.</xs:documentation>
								</xs:annotation>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="modelName" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Name of the PSI/MSI data exchange schema, e.g. mzData, nmrML.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="modelURI" type="xs:anyURI" use="required">
				<xs:annotation>
					<xs:documentation>URI of the data exchange schema</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="modelVersion" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Version number of the model supported by the CvMapping file. </xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="CvMappingRule">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="CvTerm" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>One or more terms from a CVsource that are allowed to be associated with the given element of the model. </xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="required">
				<xs:annotation>
					<xs:documentation>Unique identifier of the rule in this mapping file.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="name" type="xs:string" use="optional">
				<xs:annotation>
					<xs:documentation>Name of this rule (can be used for reporting of errors)</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="scopePath" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Element scope in the schema within which the non repeatable (isRepeatable = FALSE) condition applies.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="requirementLevel" use="required">
				<xs:annotation>
					<xs:documentation>The requirement level indicated, when the XML element exists in the instance data file, if the association with CV terms is optional (MAY), recommended (SHOULD) or mandatory (MUST). </xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="MUST"/>
						<xs:enumeration value="SHOULD"/>
						<xs:enumeration value="MAY"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="cvElementPath" type="xs:string" use="required"/>
			<xs:attribute name="cvTermsCombinationLogic" use="required">
				<xs:annotation>
					<xs:documentation>Boolean operator describing the combination logic of multiple CvTerm elements associated with the same CvMappingRule. </xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="OR"/>
						<xs:enumeration value="AND"/>
						<xs:enumeration value="XOR"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="CvTerm">
		<xs:complexType>
			<xs:attribute name="cvIdentifierRef" type="xs:IDREF" use="required">
				<xs:annotation>
					<xs:documentation>Internal reference (e.g. namespace abbreviation) to a term source file as defined in a CvReference element.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="termAccession" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>CV term accession number / identifyier as in the CV file. Usually consistimg out of a short namespace prefix and a unique number, or of a meaningful string.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="termName" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>The human readable and intelligable label. Ideally adhering to naming conventions outlined in http://www.biomedcentral.com/1471-2105</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="useTermName" type="xs:boolean" use="optional" default="false">
				<xs:annotation>
					<xs:documentation>Boolean to set whether the check is done on the termName (TRUE) or on the termAccession (FALSE and default). </xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="useTerm" type="xs:boolean" use="required">
				<xs:annotation>
					<xs:documentation>This attribute indicates whether the term itself can be used to annotate data (TRUE) or not (FALSE). This latter case may happen when a term, parent of valid terms for annotation, is mentioned to keep the mapping concise.  </xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="allowChildren" type="xs:boolean" use="required">
				<xs:annotation>
					<xs:documentation>This attribute indicates whether the children of the described term are allowed to annotate data (TRUE) or not (FALSE). </xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="isRepeatable" type="xs:boolean" use="optional" default="true">
				<xs:annotation>
					<xs:documentation>Value is 'True' when a term can be repeated in the same instance of the associated XML element.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="CvReference">
		<xs:complexType>
			<xs:attribute name="cvIdentifier" type="xs:ID" use="required">
				<xs:annotation>
					<xs:documentation>Short label for the CV or namespace, this should correspond to a cvIdentifier attribute of CvTerm</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="cvName" type="xs:string" use="required">
				<xs:annotation>
					<xs:documentation>Full descriptive name for the CV.</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nmrML/nmrML/tools/Validator/nmr-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="https://psidev.svn.sourceforge.net/svnroot/psidev/psi/tools/current/xsl/cv-mapping/CvMappingRules.xsl" type="text/xsl"?>
<!-- 
CVInspector -cv_files msi-nmr.obo -cv_names NMR -mapping_file nmr-mapping.xml -html mapping_and_cv.html
-->

<CvMapping xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.psidev.info/files/validator/CvMapping.xsd" modelName="nmrML.xsd" modelURI="https://raw.github.com/nmrML/nmrML/master/xml-schemata/nmrML.xsd" modelVersion="0.1.0">

    <CvReferenceList>
      <CvReference cvName="NMR" cvIdentifier="NMR"/>
      <CvReference cvName="PATO" cvIdentifier="PATO"/>
      <CvReference cvName="UO" cvIdentifier="UO"/>    
    </CvReferenceList>

    <CvMappingRuleList>

      <!-- sourceFile -->

      <CvMappingRule id="sourceFile_must" 
		     cvElementPath="/nmrML/sourceFileList/sourceFile/cvParam/@accession" 
		     requirementLevel="MUST" 
		     scopePath="/nmrML/sourceFileList/sourceFile/" 
		     cvTermsCombinationLogic="AND">
	<CvTerm termAccession="NMR:1400285" 
		useTerm="false" 
		termName="NMR software data format" 
		isRepeatable="false" 
		allowChildren="true" 
		cvIdentifierRef="NMR"></CvTerm>
      </CvMappingRule>

      <!-- sourceFile -->

      <CvMappingRule id="sourceFile_may" 
		     cvElementPath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/pulseSequence/cvParam@accession" 
		     requirementLevel="MAY" 
		     scopePath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/pulseSequence/" 
		     cvTermsCombinationLogic="AND">
	<CvTerm termAccession="NMR:1400285" 
		useTerm="false" 
		termName="NMR software data format" 
		isRepeatable="false" 
		allowChildren="true" 
		cvIdentifierRef="NMR"></CvTerm>
	<CvTerm termAccession="NMR:1002006" 
		useTerm="false" 
		termName="acquisition parameter file format"
		isRepeatable="false" 
		allowChildren="true" 
		cvIdentifierRef="NMR"></CvTerm>
      </CvMappingRule>
      
      <!-- software-->

      <CvMappingRule id="software_must" 
		     cvElementPath="/nmrML/softwareList/software/cvParam/@accession" 
		     requirementLevel="MUST" 
		     scopePath="/nmrML/softwareList/software" 
		     cvTermsCombinationLogic="AND">
	<CvTerm termAccession="NMR:1000531" 
		useTerm="false" 
		termName="software" 
		isRepeatable="false" 
		allowChildren="true" 
		cvIdentifierRef="NMR"></CvTerm>
      </CvMappingRule>

      <CvMappingRule id="software_must" 
		     cvElementPath="/nmrML/softwareList/software@accession" 
		     requirementLevel="MUST" 
		     scopePath="/nmrML/softwareList/" 
		     cvTermsCombinationLogic="AND">
	<CvTerm termAccession="NMR:1000531" 
		useTerm="false" 
		termName="software" 
		isRepeatable="false" 
		allowChildren="true" 
		cvIdentifierRef="NMR"></CvTerm>
      </CvMappingRule>

      <!-- instrumentConfiguration -->

      <CvMappingRule id="instrumentConfiguration_must" 
		     cvElementPath="/nmrML/instrumentConfigurationList/instrumentConfiguration/cvParam/@accession"
		     requirementLevel="MAY" 
		     scopePath="/nmrML/instrumentConfigurationList/instrumentConfiguration/"
		     cvTermsCombinationLogic="AND">
	<CvTerm termAccession="NMR:1000031" 
		useTerm="false" 
		termName="instrument model" 
		isRepeatable="false" 
		allowChildren="true" 
		cvIdentifierRef="NMR"></CvTerm>
	<CvTerm termAccession="NMR:1400014" 
		useTerm="false" 
		termName="NMR probe" 
		isRepeatable="false" 
		allowChildren="true" 
		cvIdentifierRef="NMR"></CvTerm>
      </CvMappingRule>

      <CvMappingRule id="instrumentConfiguration_may" 
		     cvElementPath="/nmrML/instrumentConfigurationList/instrumentConfiguration/cvParam/@accession"
		     requirementLevel="MAY" 
		     scopePath="/nmrML/instrumentConfigurationList/instrumentConfiguration/"
		     cvTermsCombinationLogic="AND">
	<CvTerm termAccession="NMR:1000463" 
		useTerm="false" 
		termName="instrument" 
		isRepeatable="false" 
		allowChildren="true" 
		cvIdentifierRef="NMR"></CvTerm>
      </CvMappingRule>

      <!-- Contact has no mapping, can use whatever seems fit from FOAF or whatever -->

      <CvMappingRule id="sampleAcquisitionTemperature_must" 
		     cvElementPath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/sampleAcquisitionTemperature@unitAccession" 
		     requirementLevel="MUST" 
		     scopePath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/sampleAcquisitionTemperature/" 
		     cvTermsCombinationLogic="AND">
	<CvTerm termAccession="UO:0000012" 
		useTerm="true" 
		termName="kelvin" 
		isRepeatable="false" 
		allowChildren="false" 
		cvIdentifierRef="UO"></CvTerm>
      </CvMappingRule>

      <CvMappingRule id="spinningRate_must" 
		     cvElementPath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/spinningRate@unitAccession" 
		     requirementLevel="MUST" 
		     scopePath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/spinningRate"
		     cvTermsCombinationLogic="AND">
	<CvTerm termAccession="UO:0000106"
		useTerm="true" 
		termName="hertz" 
		isRepeatable="false" 
		allowChildren="false" 
		cvIdentifierRef="UO"></CvTerm>
      </CvMappingRule>

      <CvMappingRule id="relaxationDelay_must" 
		     cvElementPath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/relaxationDelay@unitAccession" 
		     requirementLevel="MUST" 
		     scopePath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/relaxationDelay"
		     cvTermsCombinationLogic="AND">
	<CvTerm termAccession="UO:0000010"
		useTerm="true" 
		termName="second" 
		isRepeatable="false" 
		allowChildren="false" 
		cvIdentifierRef="UO"></CvTerm>
      </CvMappingRule>

      <CvMappingRule id="pulseSequence_may" 
		     cvElementPath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/pulseSequence/cvParam@accession" 
		     requirementLevel="MAY" 
		     scopePath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/pulseSequence"
		     cvTermsCombinationLogic="AND">
	<CvTerm termAccession="NMR:1000226"
		useTerm="false" 
		termName="first transient of the tnnoesy-presaturation pulse sequence UPDATE TO PARENT TERM !!" 
		isRepeatable="false" 
		allowChildren="true" 
		cvIdentifierRef="UO"></CvTerm>
      </CvMappingRule>

      <CvMappingRule id="acquisitionNucleus_must" 
		     cvElementPath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/DirectDimensionParameterSet/acquisitionNucleus@accession" 
		     requirementLevel="MAY" 
		     scopePath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/DirectDimensionParameterSet/acquisitionNucleus"
		     cvTermsCombinationLogic="AND">
	<CvTerm termAccession="NMR:1400083"
		useTerm="false" 
		termName="acquisition nucleus"
		isRepeatable="false" 
		allowChildren="true" 
		cvIdentifierRef="UO"></CvTerm>
      </CvMappingRule>

      <CvMappingRule id="decouplingMethod_must" 
		     cvElementPath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/DirectDimensionParameterSet/decouplingMethod@accession" 
		     requirementLevel="MAY" 
		     scopePath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/DirectDimensionParameterSet/decouplingMethod"
		     cvTermsCombinationLogic="AND">
	<CvTerm termAccession="NMR:1000000"
		useTerm="false" 
		termName="decoupling method"
		isRepeatable="false" 
		allowChildren="true" 
		cvIdentifierRef="UO"></CvTerm>
      </CvMappingRule>

      <!-- must add the mapping for this -->
      <!-- <samplingStrategy accession="?" cvRef="NMRCV" name="uniform"/> -->
      <CvMappingRule id="samplingStrategy_must" 
		     cvElementPath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/DirectDimensionParameterSet/samplingStrategy@accession" 
		     requirementLevel="MAY" 
		     scopePath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/DirectDimensionParameterSet/samplingStrategy"
		     cvTermsCombinationLogic="AND">
	<CvTerm termAccession="NMR:1000000"
		useTerm="false" 
		termName="sampling strategy"
		isRepeatable="false" 
		allowChildren="true" 
		cvIdentifierRef="UO"></CvTerm>
      </CvMappingRule>

      <CvMappingRule id="gammaB1PulseFieldStrength_must" 
		     cvElementPath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/DirectDimensionParameterSet/gammaB1PulseFieldStrength@unitAccession" 
		     requirementLevel="MUST" 
		     scopePath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/DirectDimensionParameterSet/gammaB1PulseFieldStrength"
		     cvTermsCombinationLogic="AND">
	<CvTerm termAccession="UO:0000228"
		useTerm="true" 
		termName="tesla" 
		isRepeatable="false" 
		allowChildren="false" 
		cvIdentifierRef="UO"></CvTerm>
      </CvMappingRule>

      <CvMappingRule id="sweepWidth_must" 
		     cvElementPath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/DirectDimensionParameterSet/sweepWidth@unitAccession" 
		     requirementLevel="MUST" 
		     scopePath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/DirectDimensionParameterSet/sweepWidth"
		     cvTermsCombinationLogic="AND">
	<CvTerm termAccession="UO:0000106"
		useTerm="true" 
		termName="hertz" 
		isRepeatable="false" 
		allowChildren="false" 
		cvIdentifierRef="UO"></CvTerm>
      </CvMappingRule>

      <CvMappingRule id="irradiationFrequency_must" 
		     cvElementPath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/DirectDimensionParameterSet/irradiationFrequency@unitAccession" 
		     requirementLevel="MUST" 
		     scopePath="/nmrML/acquisition/acquisition1D/acquisitionParameterSet/DirectDimensionParameterSet/irradiationFrequency"
		     cvTermsCombinationLogic="AND">
	<CvTerm termAccession="UO:0000106"
		useTerm="true" 
		termName="hertz" 
		isRepeatable="false" 
		allowChildren="false" 
		cvIdentifierRef="UO"></CvTerm>
      </CvMappingRule>
      
    </CvMappingRuleList>
</CvMapping>
